import { useEffect, useRef, useState } from 'react';
import * as echarts from 'echarts/core';
import { CandlestickChart, LineChart, BarChart } from 'echarts/charts';
import { GridComponent, TooltipComponent, DataZoomComponent, LegendComponent } from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import { Candle } from '../../../packages/domain/types';
import { request, useSession, cacheCandles, cachedCandles } from './transport';
import { useWorkspace } from './workspace';
import { useTranslate, Empty } from './ui';
echarts.use([CandlestickChart,LineChart,BarChart,GridComponent,TooltipComponent,DataZoomComponent,LegendComponent,CanvasRenderer]);
const periods=[['1m','分时'],['5m','5m'],['60m','60m'],['day','日线'],['week','周线'],['month','月线']];
export function Chart({symbol}:{symbol:string}) {
  const t=useTranslate();const {theme,upIsRed,reducedMotion,language}=useWorkspace();const session=useSession();
  const element=useRef<HTMLDivElement>(null);const instance=useRef<echarts.ECharts|null>(null);const [period,setPeriod]=useState('day');const [indicator,setIndicator]=useState('MA');const [adjusted,setAdjusted]=useState(false);const [bars,setBars]=useState<Candle[]>([]);const [error,setError]=useState('');const [replay,setReplay]=useState(false);const [playing,setPlaying]=useState(false);const [cursor,setCursor]=useState(30);const [speed,setSpeed]=useState(4);
  useEffect(()=>{let cancelled=false,freshLoaded=false;setBars([]);setError('');const cacheKey=`${symbol}:${period}:${adjusted}`;void cachedCandles<Candle>(cacheKey).then(values=>{if(!cancelled&&!freshLoaded&&values.length)setBars(values);});const load=()=>void request<Candle[]>(`/history/${encodeURIComponent(symbol)}?interval=${period}&adjusted=${adjusted}&all=${['day','week','month'].includes(period)}`).then(result=>{if(!cancelled){freshLoaded=true;setBars(result.slice(-600));setError('');void cacheCandles(cacheKey,result);}}).catch(failure=>{if(!cancelled)setError(failure.message);});load();const timer=setInterval(load,5000);return()=>{cancelled=true;clearInterval(timer);};},[symbol,period,adjusted,session.principal?.owner]);
  useEffect(()=>{if(!element.current)return;const chart=echarts.init(element.current);instance.current=chart;const observer=new ResizeObserver(()=>chart.resize());observer.observe(element.current);return()=>{observer.disconnect();chart.dispose();instance.current=null;};},[]);
  useEffect(()=>{if(!instance.current)return;const source=replay?bars.slice(0,cursor):bars;const labels=source.map(bar=>new Date(bar.time).toLocaleString(language==='en'?'en-GB':'zh-CN',{month:'2-digit',day:'2-digit',...(['1m','5m','60m'].includes(period)?{hour:'2-digit',minute:'2-digit'}:{})}));
    const up=upIsRed?'#fa7670':'#58c9a0';const down=upIsRed?'#58c9a0':'#fa7670';const muted=theme==='dark'?'#718194':'#637181';const line=theme==='dark'?'#26303b':'#dce1e6';const closes=source.map(bar=>bar.close/100);
    const series:any[]=[period==='1m'?{name:'Price',type:'line',data:closes,symbol:'none',lineStyle:{width:2,color:'#e5af4b'},areaStyle:{color:'rgba(229,175,75,.06)'}}:{name:'OHLC',type:'candlestick',data:source.map(bar=>[bar.open/100,bar.close/100,bar.low/100,bar.high/100]),itemStyle:{color:up,color0:down,borderColor:up,borderColor0:down}}];
    if(indicator==='MA')for(const [span,color]of [[5,'#e5af4b'],[20,'#8faee3']]as const)series.push({name:'MA'+span,type:'line',data:closes.map((_,index)=>index<span-1?null:closes.slice(index-span+1,index+1).reduce((sum,value)=>sum+value,0)/span),symbol:'none',lineStyle:{width:1,color}});
    if(indicator==='BOLL'){const mid=closes.map((_,index)=>index<19?null:closes.slice(index-19,index+1).reduce((sum,value)=>sum+value,0)/20);for(const [offset,name]of [[0,'MID'],[2,'UPPER'],[-2,'LOWER']]as const)series.push({name,type:'line',symbol:'none',data:mid.map((value,index)=>value===null?null:value+offset*Math.sqrt(closes.slice(index-19,index+1).reduce((sum,price)=>sum+(price-value)**2,0)/20)),lineStyle:{width:1,color:offset===0?'#e5af4b':'#8faee3'}});}
    series.push(indicator==='RSI'?{name:'RSI14',type:'line',xAxisIndex:1,yAxisIndex:1,symbol:'none',data:closes.map((_,index)=>{if(index<14)return null;let gain=0,loss=0;for(let offset=index-13;offset<=index;offset++){const change=closes[offset]-closes[offset-1];gain+=Math.max(0,change);loss+=Math.max(0,-change);}return loss===0?100:100-100/(1+gain/loss);}),lineStyle:{color:'#e5af4b',width:1}}:{name:'Volume',type:'bar',xAxisIndex:1,yAxisIndex:1,data:source.map(bar=>({value:bar.volume,itemStyle:{color:bar.close>=bar.open?up:down,opacity:.45}}))});
    instance.current.setOption({animation:!reducedMotion&&false,backgroundColor:'transparent',legend:{top:6,textStyle:{color:muted,fontSize:10},itemWidth:12,itemHeight:7},tooltip:{trigger:'axis',backgroundColor:theme==='dark'?'#202833':'#fff',borderColor:line,textStyle:{color:theme==='dark'?'#e5e8ed':'#15212e'},axisPointer:{type:'cross'}},grid:[{left:56,right:18,top:36,height:'61%'},{left:56,right:18,top:'76%',height:'13%'}],xAxis:[{type:'category',data:labels,boundaryGap:true,axisLabel:{color:muted,fontSize:10},axisLine:{lineStyle:{color:line}},splitLine:{show:false}},{type:'category',data:labels,gridIndex:1,axisLabel:{show:false},axisLine:{lineStyle:{color:line}}}],yAxis:[{scale:true,axisLabel:{color:muted,fontSize:10,formatter:(value:number)=>value.toFixed(2)},splitLine:{lineStyle:{color:line,type:'dashed'}}},{scale:true,gridIndex:1,axisLabel:{color:muted,fontSize:9},splitLine:{show:false}}],dataZoom:[{type:'inside',xAxisIndex:[0,1],start:Math.max(0,100-180/Math.max(1,source.length)*100),end:100},{type:'slider',xAxisIndex:[0,1],height:14,bottom:2,showDetail:false,borderColor:line,backgroundColor:'transparent',fillerColor:'rgba(229,175,75,.08)',handleStyle:{color:'#e5af4b'}}],series},true);
  },[bars,theme,upIsRed,reducedMotion,language,period,indicator,replay,cursor]);
  useEffect(()=>{if(!replay||!playing)return;const timer=setInterval(()=>setCursor(value=>{if(value>=bars.length){setPlaying(false);return value;}return Math.min(bars.length,value+speed);}),500);return()=>clearInterval(timer);},[replay,playing,speed,bars.length]);
  return <section className="chart-panel"><div className="chart-tools"><div className="segmented">{periods.map(([value,label])=><button key={value} className={period===value?'active':''} onClick={()=>{setPeriod(value);setReplay(false);}}>{language==='en'&&label==='日线'?'D':language==='en'&&label==='周线'?'W':language==='en'&&label==='月线'?'M':label}</button>)}</div><div className="chart-options"><select aria-label="指标" value={indicator} onChange={event=>setIndicator(event.target.value)}><option>MA</option><option>BOLL</option><option>RSI</option><option value="none">—</option></select><button className={adjusted?'text-button amber':'text-button'} onClick={()=>setAdjusted(!adjusted)}>{adjusted?'前复权':'不复权'}</button><button className="text-button" onClick={()=>{setReplay(!replay);setCursor(30);setPlaying(false);}}>{t('复盘回放')}</button></div></div><div className="chart-canvas" ref={element} aria-label="股票行情图表"/>{bars.length===0&&<div className="chart-empty"><Empty>{error||t('等待行情同步')}</Empty></div>}{replay&&<div className="replay-controls"><button onClick={()=>setPlaying(!playing)}>{t(playing?'暂停':'播放')}</button><input aria-label="回放进度" type="range" min="1" max={Math.max(1,bars.length)} value={cursor} onChange={event=>setCursor(Number(event.target.value))}/><select aria-label="回放速度" value={speed} onChange={event=>setSpeed(Number(event.target.value))}>{[1,4,16].map(value=><option key={value} value={value}>{value}×</option>)}</select><span>{Math.min(cursor,bars.length)} / {bars.length}</span></div>}</section>;
}
