import { useEffect, useRef, useState } from 'react';
import { Instrument, OrderType, Side } from '../../../packages/domain/types';
import { useSession, command, request } from './transport';
import { useWorkspace, setWorkspace, toggleWatch, updateDraft, cents } from './workspace';
import { Change, Empty, Icon, money, Panel, useTranslate } from './ui';
import { Chart } from './Chart';
const orderTypes:[OrderType,string][]=[['market','市价单'],['limit','限价单'],['stop','止损单'],['stop-limit','止损限价'],['fok','FOK'],['ioc','IOC'],['iceberg','冰山单']];
export function Trade({notify}:{notify:(text:string,kind?:string)=>void}) {
  const session=useSession();const workspace=useWorkspace();const t=useTranslate();const [company,setCompany]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [bottomTab,setBottomTab]=useState('positions');
  const snapshot=session.snapshot;if(!snapshot)return <Empty>{t('等待行情同步')}</Empty>;
  const instrument=snapshot.instruments.find(item=>item.symbol===workspace.symbol);if(!instrument)return <Empty>请选择市场标的</Empty>;
  const quote=snapshot.quotes[instrument.symbol];const held=snapshot.accounts[workspace.market];
  const list=snapshot.instruments.filter(item=>item.market===workspace.market&&(!workspace.industry||item.industry===workspace.industry)&&(!workspace.watchOnly||workspace.watch.includes(item.symbol))&&(!workspace.search||[item.name,item.symbol,item.code,item.industry].some(value=>value.toLowerCase().includes(workspace.search.toLowerCase()))));
  const select=(item:Instrument)=>{setWorkspace({symbol:item.symbol});setSearchOpen(false);};
  return <><div className="trading-grid">
    <aside className={'watch-panel panel '+(searchOpen?'mobile-open':'')}><div className="panel-heading"><div className="segmented"><button className={!workspace.watchOnly?'active':''} onClick={()=>setWorkspace({watchOnly:false})}>{t('全部')}</button><button className={workspace.watchOnly?'active':''} onClick={()=>setWorkspace({watchOnly:true})}>{t('自选')}</button></div><button className="mobile-only icon-button" aria-label="关闭标的列表" onClick={()=>setSearchOpen(false)}><Icon name="close"/></button></div><label className="search-field"><Icon name="search"/><input aria-label="搜索股票" placeholder={t('搜索名称 / 代码')} value={workspace.search} onChange={event=>setWorkspace({search:event.target.value})}/></label><label className="sector-filter"><select aria-label="筛选行业" value={workspace.industry} onChange={event=>setWorkspace({industry:event.target.value})}><option value="">全部行业 · {snapshot.instruments.filter(item=>item.market===workspace.market).length} 支</option>{[...new Set(snapshot.instruments.filter(item=>item.market===workspace.market).map(item=>item.industry))].map(industry=><option key={industry} value={industry}>{industry} · {snapshot.instruments.filter(item=>item.industry===industry&&item.market===workspace.market).length}</option>)}</select></label><div className="watch-columns"><span>名称 / 代码</span><span>最新 / 涨跌</span></div><div className="watch-list">{list.map(item=><div key={item.symbol} className={'watch-row '+(item.symbol===instrument.symbol?'selected':'')}><button aria-label={'自选 '+item.name} className={'watch-star '+(workspace.watch.includes(item.symbol)?'starred':'')} onClick={()=>toggleWatch(item.symbol)}><Icon name="star"/></button><button className="watch-select" onClick={()=>select(item)}><span><strong>{item.name}</strong><small>{item.code} · {item.industry}</small></span><span className="number"><strong className={snapshot.quotes[item.symbol].change>=0?'up':'down'}>{money(snapshot.quotes[item.symbol].price)}</strong><small><Change value={snapshot.quotes[item.symbol].change}/></small></span></button></div>)}{!list.length&&<Empty>{t('暂无记录')}</Empty>}</div></aside>
    <main className="instrument-workspace panel"><div className="instrument-heading"><div><button className="instrument-picker" onClick={()=>setSearchOpen(true)}><h2>{instrument.name}</h2><span className="mobile-only">⌄</span></button><span className="muted mono small">{instrument.code} / {instrument.market} <span className="chip">{instrument.industry}</span></span></div><div className="instrument-price"><strong className={quote.change>=0?'up':'down'}>{money(quote.price)}</strong><Change value={quote.change}/></div></div><div className="quote-strip"><span>开盘 <b>{money(quote.open)}</b></span><span>最高 <b className="up">{money(quote.high)}</b></span><span>最低 <b className="down">{money(quote.low)}</b></span><span>成交量 <b>{quote.volume.toLocaleString()}</b></span><span>估值 PE <b>{quote.pe.toFixed(1)}</b></span></div><Chart symbol={instrument.symbol}/><div className="instrument-meta"><button className="text-button" onClick={()=>setCompany(!company)}>{t('公司资料')} <span>↗</span></button><span className="muted small">{t('财报预期')} <b className={quote.earningsGrowth>=0?'up':'down'}>{(quote.earningsGrowth*100).toFixed(1)}%</b></span></div>{company&&<div className="company-details"><strong>{instrument.name}</strong><p>{instrument.description}</p><dl><div><dt>主营业务</dt><dd>{instrument.riskProfile?.business??instrument.industry}</dd></div><div><dt>消息敏感因素</dt><dd>{instrument.riskProfile?.newsKinds.join(' / ')??'经营变化'}</dd></div><div><dt>参考年股息率</dt><dd>{((instrument.riskProfile?.dividendYield??0)*100).toFixed(1)}%</dd></div><div><dt>上市日期</dt><dd>{instrument.listedAt}</dd></div><div><dt>基本面参考值</dt><dd>{money(quote.fairValue)}</dd></div><div><dt>行业周期</dt><dd>{['扩张','顶峰','收缩','谷底'][snapshot.markets[workspace.market].sectors[instrument.industry]?.cycle??0]}</dd></div></dl></div>}</main>
    <aside className={'ticket-panel panel '+(workspace.ticketOpen?'mobile-open':'')}><div className="panel-heading"><h2>{t('盘口')} / {t('账户')}</h2><button aria-label="关闭交易面板" className="mobile-only icon-button" onClick={()=>setWorkspace({ticketOpen:false})}><Icon name="close"/></button><span className="chip">{snapshot.markets[workspace.market].clock.phase}</span></div><Book symbol={instrument.symbol}/><Ticket symbol={instrument.symbol} notify={notify}/></aside>
  </div><Panel title="" className="blotter" action={<div className="segmented"><button className={bottomTab==='positions'?'active':''} onClick={()=>setBottomTab('positions')}>{t('持仓')} <small>{held?.positions.length??0}</small></button><button className={bottomTab==='orders'?'active':''} onClick={()=>setBottomTab('orders')}>{t('挂单')} <small>{snapshot.orders.filter(order=>['pending','partial'].includes(order.status)&&snapshot.instruments.find(item=>item.symbol===order.symbol)?.market===workspace.market).length}</small></button><button className={bottomTab==='trades'?'active':''} onClick={()=>setBottomTab('trades')}>{t('成交记录')}</button></div>}>
    <div className="table-scroll"><table><thead><tr>{(bottomTab==='positions'?['标的','持仓 / 可卖','成本 / 最新','浮动盈亏','操作']:bottomTab==='orders'?['标的','方向 / 类型','已成交 / 总量','价格','状态 / 操作']:['标的','方向','成交数量','成交价格','交易日']).map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{bottomTab==='positions'?held?.positions.map(position=><tr key={position.symbol}><td><strong>{snapshot.instruments.find(item=>item.symbol===position.symbol)?.name}</strong><small>{position.symbol}</small></td><td className="mono">{position.quantity} / {position.sellable}{position.shortQuantity>0&&<small>空头 {position.shortQuantity}</small>}</td><td className="mono">{money(position.cost)} / {money(snapshot.quotes[position.symbol].price)}</td><td className={position.pnl>=0?'up mono':'down mono'}>{money(position.pnl)}</td><td><button className="text-button" onClick={()=>{setWorkspace({symbol:position.symbol,ticketOpen:true});updateDraft(position.symbol,{side:position.shortQuantity?'cover':'sell',quantity:String(position.shortQuantity||position.sellable)});}}>{t(position.shortQuantity?'平空':'卖出')} ↗</button></td></tr>):bottomTab==='orders'?snapshot.orders.filter(order=>snapshot.instruments.find(item=>item.symbol===order.symbol)?.market===workspace.market).slice(0,20).map(order=><tr key={order.id}><td>{snapshot.instruments.find(item=>item.symbol===order.symbol)?.name}<small>{order.id}</small></td><td>{t(({buy:'买入',sell:'卖出',short:'做空',cover:'平空'}as const)[order.side])}<small>{order.type}</small></td><td className="mono">{order.filled} / {order.quantity}</td><td className="mono">{money(order.averagePrice||order.price)}</td><td><span className="chip">{order.status}</span>{['pending','partial'].includes(order.status)&&<button className="text-button" disabled={session.connection!=='live'} onClick={()=>void command({kind:'cancel',orderId:order.id}).then(()=>notify('订单已撤销')).catch(error=>notify(error.message,'error'))}>{t('撤单')}</button>}{order.error&&<small>{order.error}</small>}</td></tr>):snapshot.trades.filter(trade=>snapshot.instruments.find(item=>item.symbol===trade.symbol)?.market===workspace.market).slice(0,20).map(trade=><tr key={trade.id}><td>{snapshot.instruments.find(item=>item.symbol===trade.symbol)?.name}<small>{trade.id}</small></td><td>{trade.buyer===held?.id?t(trade.buySide==='cover'?'平空':'买入'):t(trade.sellSide==='short'?'做空':'卖出')}</td><td className="mono">{trade.quantity}</td><td className="mono">{money(trade.price)}</td><td className="mono">D{trade.day}</td></tr>)}</tbody></table></div>{(bottomTab==='positions'&&!held?.positions.length||bottomTab==='orders'&&!snapshot.orders.length||bottomTab==='trades'&&!snapshot.trades.length)&&<Empty>{t('暂无记录')}</Empty>}</Panel>
  <div className="mobile-trade-bar"><span>{instrument.name}<b className="mono">{money(quote.price)}</b></span><button className="buy-button" onClick={()=>{updateDraft(instrument.symbol,{side:'buy'});setWorkspace({ticketOpen:true});}}>{t('买入')}</button><button className="sell-button" onClick={()=>{updateDraft(instrument.symbol,{side:'sell'});setWorkspace({ticketOpen:true});}}>{t('卖出')}</button></div></>;
}
function Book({symbol}:{symbol:string}){const [book,setBook]=useState<{asks:{price:number;quantity:number}[];bids:{price:number;quantity:number}[]}>({asks:[],bids:[]});const session=useSession();useEffect(()=>{let cancelled=false;const load=()=>void request('/book/'+symbol).then(value=>{if(!cancelled)setBook(value);}).catch(()=>{});load();const timer=setInterval(load,3000);return()=>{cancelled=true;clearInterval(timer);};},[symbol,session.principal?.owner]);return <div className="order-book">{[...book.asks].reverse().map((level,index)=><button key={'ask'+index} className="book-row ask" onClick={()=>updateDraft(symbol,{type:'limit',price:(level.price/100).toFixed(2)})}><i style={{width:Math.min(90,level.quantity/24)+'%'}}/><span>卖 {book.asks.length-index}</span><b>{money(level.price)}</b><span>{level.quantity}</span></button>)}<div className="book-mid"><strong>{money(session.snapshot?.quotes[symbol]?.price)}</strong><span className="small muted">实际挂单深度</span></div>{book.bids.map((level,index)=><button key={'bid'+index} className="book-row bid" onClick={()=>updateDraft(symbol,{type:'limit',price:(level.price/100).toFixed(2)})}><i style={{width:Math.min(90,level.quantity/24)+'%'}}/><span>买 {index+1}</span><b>{money(level.price)}</b><span>{level.quantity}</span></button>)}</div>;}
function Ticket({symbol,notify}:{symbol:string;notify:(text:string,kind?:string)=>void}) {
  const session=useSession();const workspace=useWorkspace();const t=useTranslate();const [submitting,setSubmitting]=useState(false);const guard=useRef(false);const [estimate,setEstimate]=useState<any>(null);
  const draft=workspace.drafts[workspace.market+':'+symbol]??{type:'market' as OrderType,side:'buy' as Side,quantity:'100',price:'',trigger:'',display:'20'};
  const phase=session.snapshot?.markets[workspace.market].clock.phase;const held=session.snapshot?.accounts[workspace.market];const blocked=session.connection!=='live'||!held||['closed','pre-open'].includes(phase??'closed');
  function input(){const quantity=Number(draft.quantity);if(!Number.isSafeInteger(quantity)||quantity<1)throw new Error('数量必须为正整数');return {symbol,side:draft.side,type:draft.type,quantity,...(['limit','stop-limit','fok','ioc','iceberg'].includes(draft.type)?{price:cents(draft.price)}:{}),...(['stop','stop-limit'].includes(draft.type)?{triggerPrice:cents(draft.trigger)}:{}),...(draft.type==='iceberg'?{displayQuantity:Number(draft.display)}:{})};}
  useEffect(()=>{let cancelled=false;const timer=setTimeout(()=>{if(blocked)return;try {void request('/orders/estimate',{market:workspace.market,input:input()}).then(value=>{if(!cancelled)setEstimate(value);}).catch(()=>{if(!cancelled)setEstimate(null);});}catch{setEstimate(null);}},350);return()=>{cancelled=true;clearTimeout(timer);};},[symbol,draft.type,draft.side,draft.quantity,draft.price,draft.trigger,draft.display,workspace.market,blocked]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(guard.current||blocked)return;guard.current=true;setSubmitting(true);try {const result=await command({kind:'order',market:workspace.market,input:input()});notify(result.order.filled?`成交 ${result.order.filled} / ${result.order.quantity} 股 · ${money(result.order.averagePrice)}`:`订单状态：${result.order.status}${result.order.error?' · '+result.order.error:''}`);setWorkspace({ticketOpen:false});}catch(error){notify(error instanceof Error?error.message:'下单失败','error');}finally{guard.current=false;setSubmitting(false);}};
  return <form className="order-ticket" onSubmit={submit}><div className="ticket-sides">{(['buy','sell','short','cover']as Side[]).map(side=><button type="button" key={side} disabled={workspace.market==='CN'&&['short','cover'].includes(side)} className={draft.side===side?'active '+(side==='buy'||side==='cover'?'buy':'sell'):''} onClick={()=>updateDraft(symbol,{side})}>{t(({buy:'买入',sell:'卖出',short:'做空',cover:'平空'}as const)[side])}</button>)}</div><label>{t('市价单')} / {t('限价单')}<select aria-label="订单类型" value={draft.type} onChange={event=>updateDraft(symbol,{type:event.target.value as OrderType,price:draft.price||(session.snapshot?.quotes[symbol].price!/100).toFixed(2)})}>{orderTypes.map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</select></label><label>{t('数量')}<input aria-label="订单数量" type="number" min="1" max="100000" step="1" value={draft.quantity} onChange={event=>updateDraft(symbol,{quantity:event.target.value})}/></label>{['limit','stop-limit','fok','ioc','iceberg'].includes(draft.type)&&<label>{t('限价')}<input aria-label="订单限价" inputMode="decimal" value={draft.price} onChange={event=>updateDraft(symbol,{price:event.target.value})}/></label>}{['stop','stop-limit'].includes(draft.type)&&<label>{t('触发价')}<input aria-label="订单触发价" inputMode="decimal" value={draft.trigger} onChange={event=>updateDraft(symbol,{trigger:event.target.value})}/></label>}{draft.type==='iceberg'&&<label>{t('显示数量')}<input aria-label="冰山显示数量" type="number" min="1" value={draft.display} onChange={event=>updateDraft(symbol,{display:event.target.value})}/></label>}<div className="ticket-summary"><div><span>{t('可用资金')}</span><strong>{money(held?.available)}</strong></div><div><span>{t('预计费用')}</span><strong>{estimate?.valid?money(estimate.fee):'—'}</strong></div><div><span>预计成交</span><strong>{estimate?.valid?estimate.filled+' / '+draft.quantity:'—'}</strong></div></div>{estimate?.valid===false&&<p className="inline-error">{estimate.error}</p>}<button className={'submit-order '+(draft.side==='buy'||draft.side==='cover'?'buy':'sell')} disabled={blocked||submitting} type="submit">{t(submitting?'正在提交':blocked?'只读模式':'提交订单')} <Icon name="arrow"/></button><p className="ticket-footnote">{workspace.market==='CN'?'A股 T+1 · ±10% 涨跌停':'T+0 · 融资与做空有保证金风险'}<br/>费用与可用资金由服务器预估，成交前重新校验。</p></form>;
}
