import { useWorkspace } from './workspace';
import { ReactNode } from 'react';
const paths:Record<string,ReactNode>={chart:<><path d="M3 18h18M5 14l5-5 4 3 6-8"/><path d="M16 4h4v4"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18M16 13h5M17 16h1"/></>,cup:<><path d="M7 3h10v6a5 5 0 0 1-10 0V3zM12 14v6M8 21h8M7 5H3v3a4 4 0 0 0 4 4M17 5h4v3a4 4 0 0 1-4 4"/></>,grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,user:<><circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>,search:<><circle cx="10" cy="10" r="6"/><path d="M15 15l6 6"/></>,close:<path d="M5 5l14 14M5 19L19 5"/>,arrow:<path d="M4 12h16M14 6l6 6-6 6"/>,star:<path d="m12 3 3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1z"/>,check:<path d="m4 12 5 5L20 6"/>,signal:<><path d="M4 20v-4M9 20v-8M14 20V8M19 20V4"/></>};
export function Icon({name}:{name:string}){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{paths[name]??paths.chart}</svg>;}
export function money(value:number|null|undefined,currency=''){return value==null?'—':currency+(value/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});}
export function percent(value:number){return (value>=0?'+':'')+(value*100).toFixed(2)+'%';}
export function Change({value}:{value:number}){return <span className={value>=0?'up':'down'}>{value>=0?'↗':'↘'} {percent(value)}</span>;}
const translations:Record<string,[string,string]>={
 '交易大厅':['Trading','交易大廳'],'资产账本':['Portfolio','資產賬本'],'赛季竞技':['Competition','賽季競技'],'策略研究':['Research','策略研究'],'个人中心':['Profile','個人中心'],'行情':['Markets','行情'],'资产':['Assets','資產'],'赛事':['Seasons','賽事'],'我的':['Profile','我的'],
 '买入':['Buy','買入'],'卖出':['Sell','賣出'],'做空':['Short','做空'],'平空':['Cover','平空'],'市价单':['Market','市價單'],'限价单':['Limit','限價單'],'止损单':['Stop','止損單'],'止损限价':['Stop limit','止損限價'],'冰山单':['Iceberg','冰山單'],
 '数量':['Quantity','數量'],'限价':['Limit price','限價'],'触发价':['Trigger price','觸發價'],'显示数量':['Display quantity','顯示數量'],'预计费用':['Est. fees','預計費用'],'可用资金':['Available cash','可用資金'],'持仓':['Positions','持倉'],'挂单':['Orders','掛單'],'成交记录':['Trades','成交記錄'],'撤单':['Cancel','撤單'],'全部':['All','全部'],'自选':['Watchlist','自選'],
 '搜索名称 / 代码':['Search name / code','搜尋名稱 / 代碼'],'交易工作台':['Trading workspace','交易工作台'],'市场事件':['Market events','市場事件'],'深色':['Dark','深色'],'浅色':['Light','淺色'],'退出账号':['Sign out','退出賬號'],'安全重试':['Retry safely','安全重試'],'同步中':['Syncing','同步中'],'实时连接':['Live','實時連接'],'只读模式':['Read only','唯讀模式'],'提交订单':['Submit order','提交訂單'],'正在提交':['Submitting','正在提交'],'合并资产':['Total assets','合併資產'],'今日盈亏':['Today P&L','今日盈虧'],'总收益':['Total return','總收益'],'公司资料':['Company','公司資料'],'财报预期':['Earnings','財報預期'],'暂无记录':['No records','暫無記錄'],'等待行情同步':['Waiting for sync','等待行情同步'],
 '货币基金':['Money market fund','貨幣基金'],'指数 ETF':['Index ETF','指數 ETF'],'申购':['Subscribe','申購'],'赎回':['Redeem','贖回'],'跨市场划转':['Transfer','跨市場劃轉'],'开始回测':['Run backtest','開始回測'],'重新连接':['Reconnect','重新連接'],'盘口':['Order book','盤口'],'当前市场':['Market','當前市場'],'第':['Day','第'],'日':['','日'],'复盘回放':['Replay','復盤回放'],'暂停':['Pause','暫停'],'播放':['Play','播放'],'周赛':['Weekly','週賽'],'双周赛':['Fortnight','雙週賽'],'月赛':['Monthly','月賽'],'报名参赛':['Join season','報名參賽'],'排名':['Rank','排名'],'账户':['Account','賬戶'],'收益率':['Return','收益率']
};
export function useTranslate(){const {language}=useWorkspace();return (text:string)=>language==='zh-CN'?text:translations[text]?.[language==='en'?0:1]??text;}
export function Panel({title,children,action,className=''}:{title:string;children:ReactNode;action?:ReactNode;className?:string}){return <section className={'panel '+className}><div className="panel-heading"><h2>{title}</h2>{action}</div><div className="panel-body">{children}</div></section>;}
export function Empty({children}:{children:ReactNode}){return <div className="empty">{children}</div>;}
