/**
 * 新闻模板库 v3（约 190 条）
 * 三阶段：stage 0=元年(<30天 上市快乐·俏皮) / 1=成长(<150天 渐正式) / 2=成熟(专业财经)
 * 占位符：{company} {code} {industry} {C}(数字) {N}(天数) 由 NewsService 动态填充
 * type：bullish / bearish / neutral（regime 偏好）
 * symbol/industry: true 时定向冲击对应个股/行业
 */
export const NEWS_TEMPLATES: any[] = [
    // ════════════════ 元年：上市快乐（俏皮、有梗） ════════════════
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}今日敲钟上市，老板发话：「上市快乐！」请全公司喝奶茶', desc: '现场气氛组已经就位，{company}的员工人手一杯奶茶合影留念。', impact: { '公司特质': 0.03, '市场情绪': 0.02 }, symbol: true, duration: 2 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}上市首日大涨，CFO 表示买辣椒炒肉再也不看价签了', desc: '股吧里一片欢乐：「老板大气，我们跟着吃香的喝辣的！」', impact: { '市场情绪': 0.02 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '传闻：{company}楼下咖啡店改名「涨停咖啡」', desc: '据说老板是资深股民，开业立了块牌子：本店续命，不负责解套。', impact: { '公司特质': 0.01 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}发布上市首份财报：营收还行，主要是快乐值拉满', desc: '财报里专门加了一页「员工幸福指数」，董事长表示这是最重要的 KPI。', impact: { '公司特质': 0.02 }, duration: 2 },
    { stage: [0], cat: 'company', type: 'bearish', title: '{company}的吉祥物在楼下发传单，路人不买账，股价略跌', desc: '传单内容「{industry}新贵了解一下」，被网友调侃像微商。', impact: { '市场情绪': -0.015 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}上市庆典放了一整晚烟花，被居民举报后登报道歉', desc: '道歉声明写得诚恳，网友们反而觉得公司有烟火气，股价不跌反涨。', impact: { '公司特质': 0.015 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}新办公楼挂牌，大厦名字是员工投票选出来的', desc: '据说最终得票最高的是「不加班大厦」，被董事会一票否决。', impact: { '公司特质': 0.01 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}董事长直播带货自家产品，直播间在线十万人', desc: '董事长亲自上阵，带货金额破亿，网友直呼「这波是董事长の逆袭」。', impact: { '公司特质': 0.025, '市场情绪': 0.01 }, symbol: true, duration: 2 },
    { stage: [0], cat: 'company', type: 'bearish', title: '{company}年终奖发了个寂寞，员工在楼下挂横幅', desc: '横幅内容：「奋斗一年，收获成长（和空气）」，被保安迅速收走。', impact: { '公司特质': -0.02 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}把年会办成了演唱会，请来了一线歌手', desc: '员工表示「公司这波血赚，门票钱都省了」，气氛组好评如潮。', impact: { '市场情绪': 0.01 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}食堂大师傅凭手艺火出圈，被美食博主探店', desc: '大师傅的招牌红烧肉成了网红菜品，公司股价跟着「香」了起来。', impact: { '公司特质': 0.015 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}在写字楼大堂放了台游戏机，员工排队打卡', desc: '人力资源部回应：这是「提升员工幸福指数」的举措，绝对不是为了摸鱼。', impact: { '市场情绪': 0.008 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bearish', title: '{company}办公楼停电三小时，全员被迫「自愿」放假', desc: '有员工在朋友圈说「因祸得福」，但市场似乎并不买账。', impact: { '公司特质': -0.012 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}发起「内推大赛」，推荐成功奖一只金猪', desc: '内推邮箱被挤爆，HR 表示「猪」是实心的，不含糊。', impact: { '公司特质': 0.008 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}产品体验官计划上线，第一批体验官是 B 站 UP 主', desc: 'UP 主们花式整活，产品热度飙升，预约量破百万。', impact: { '公司特质': 0.02, '市场情绪': 0.01 }, symbol: true, duration: 2 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}创始人上了综艺节目，聊了聊创业初期的糗事', desc: '节目播出后「创始人表情包」走红，公司知名度大增。', impact: { '市场情绪': 0.01 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bearish', title: '{company}被爆办公室养了只「镇司猫」，但猫把重要文件抓坏了', desc: '据说文件是备份过的，虚惊一场，但股价还是抖了一下。', impact: { '公司特质': -0.01 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}参加行业展会，展台被围得水泄不通', desc: '工作人员嗓子都喊哑了，现场签约意向远超预期。', impact: { '公司特质': 0.02, '行业景气': 0.01 }, symbol: true, duration: 2 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}宣布每周五下午「创意两小时」，不设 KPI', desc: '据说这期间诞生的点子比全年例会还多，管理层大受震撼。', impact: { '公司特质': 0.012 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bearish', title: '{company}门口保安大爷退休，临走前给全公司留了封信', desc: '信里写「小伙子们，别熬夜了」，看得大家眼眶一热，股价却没什么反应。', impact: {}, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}登上热搜第一，原因是「老板发红包」', desc: '据说红包总额破百万，评论区一片「别人家的公司」。', impact: { '市场情绪': 0.015 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}在园区办了个宠物日，员工带猫狗上班', desc: '宠物们成功混进了会议室，据说会议效率反而提高了。', impact: { '市场情绪': 0.008 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bearish', title: '{company}茶水间的咖啡豆换成了速溶，员工在群里炸了锅', desc: '行政部连夜道歉，重新采购高端咖啡豆，风波才平息。', impact: { '公司特质': -0.01 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'bullish', title: '{company}新办公楼启用，带健身房、按摩椅和电竞室', desc: '员工福利拉满，招聘简历量一周翻了三倍。', impact: { '公司特质': 0.02 }, duration: 1 },
    { stage: [0], cat: 'company', type: 'neutral', title: '{company}开源了内部工具，开发者社区一片叫好', desc: 'GitHub 星标一夜破万，技术口碑大幅提升。', impact: { '公司特质': 0.018 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'bullish', title: '央行发言人说：这周先给大家放点水，把情绪托起来', desc: '市场解读为流动性宽松信号，营业部门口的老大爷笑开了花。', impact: { '宏观经济': 0.02, '市场情绪': 0.02 }, duration: 3 },
    { stage: [0], cat: 'macro', type: 'neutral', title: '证监会公告：新股民朋友们，别慌，涨跌都是成长的一部分', desc: '公告最后写着：入市有风险，但成长的道路上我们都在。', impact: { '市场情绪': 0.01 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'bullish', title: '某知名财经博主发文看好后市，评论区秒变许愿池', desc: '「祝大家都能买到涨停板！」点赞量三小时破十万。', impact: { '市场情绪': 0.025 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'neutral', title: '交易所给新上市公司送了个「上市快乐」花篮', desc: '据说花篮里插的是「步步高升」的竹子，寓意很好，大家都很开心。', impact: { '市场情绪': 0.008 }, duration: 1 },
    { stage: [0], cat: 'macro', type: 'bullish', title: '统计局公布数据：大家都忙着赚钱，消费信心高涨', desc: '分析师表示「这不是经济学，这是气氛学」，市场应声走高。', impact: { '宏观经济': 0.02 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'bearish', title: '传言央行要「收水」，股吧里人心惶惶', desc: '后来证实是谣言，但当天大盘还是被吓出了一身冷汗。', impact: { '市场情绪': -0.025 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'neutral', title: '监管部门开了场投资者教育课，讲的是「韭菜的自我修养」', desc: '课堂气氛活跃，讲师说「跌了别慌，涨了别飘」。', impact: { '市场情绪': 0.005 }, duration: 1 },
    { stage: [0], cat: 'macro', type: 'bullish', title: '国常会释放稳增长信号，市场闻风而动', desc: '机构解读：政策底已现，春天不远了。', impact: { '宏观经济': 0.025, '市场情绪': 0.015 }, duration: 3 },
    { stage: [0], cat: 'macro', type: 'neutral', title: '大盘横盘一周，股民在论坛里开起了茶话会', desc: '话题从股票聊到火锅，再从火锅聊回股票，气氛祥和。', impact: { '市场情绪': 0.005 }, duration: 1 },
    { stage: [0], cat: 'macro', type: 'bearish', title: '某明星基金经理说「别急着抄底」，评论区吵翻了', desc: '支持的认为他稳，反对的说他踏空了，市场波动加大。', impact: { '市场情绪': -0.015 }, duration: 1 },
    { stage: [0], cat: 'macro', type: 'bullish', title: '券商营业部排起了队，开户量创近期新高', desc: '新开户的很多是大学生，营业部经理笑称「后浪来了」。', impact: { '市场情绪': 0.02 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'neutral', title: '财经节目请来一位神秘嘉宾，据说点石成金', desc: '嘉宾全程打哑谜，节目收视率倒是创了新高。', impact: { '市场情绪': 0.01 }, duration: 1 },
    { stage: [0], cat: 'macro', type: 'bearish', title: '外资机构发布报告：A股估值「有点贵」', desc: '报告一出，部分资金观望，成交量有所萎缩。', impact: { '市场情绪': -0.02, '国际环境': -0.01 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'bullish', title: '散户群体喊出「牛市来了」，微信群红包满天飞', desc: '情绪高涨，量能放大，涨停家数明显增多。', impact: { '市场情绪': 0.03 }, duration: 2 },
    { stage: [0], cat: 'macro', type: 'neutral', title: '某券商研报标题走红：「一边学习，一边炒股」', desc: '研报内容中规中矩，但标题确实让人想转发。', impact: {}, duration: 1 },
    { stage: [0], cat: 'industry', type: 'bullish', title: '{industry}圈疯传新作上线，相关公司股价集体躁动', desc: '据说是一款打磨三年的重磅产品，内部人士称「这次是真的顶」。', impact: { '行业景气': 0.03 }, industry: true, duration: 3 },
    { stage: [0], cat: 'industry', type: 'neutral', title: '圈内饭局流出的消息：{industry}要搞大动作，具体不便透露', desc: '消息一出，吃瓜群众比上市公司还兴奋，股吧热度飙升。', impact: { '行业景气': 0.015 }, industry: true, duration: 2 },
    { stage: [0], cat: 'industry', type: 'bearish', title: '{industry}概念股被「玩梗」炒上热搜后回落', desc: '热度来得快去得也快，昨天追高的朋友今天在群里安静如鸡。', impact: { '市场情绪': -0.02 }, duration: 1 },
    { stage: [0], cat: 'industry', type: 'bullish', title: '{industry}行业协会办了个「行业春晚」，节目单曝光', desc: '据说压轴节目是《{industry}的明天会更好》，全员大合唱。', impact: { '行业景气': 0.015 }, industry: true, duration: 2 },
    { stage: [0], cat: 'industry', type: 'neutral', title: '{industry}从业者人均「戴表」，被调侃是行业景气度指标', desc: '有人统计发现，行业越火，从业者的表越贵，于是「表价指数」诞生了。', impact: { '行业景气': 0.008 }, industry: true, duration: 1 },
    { stage: [0], cat: 'industry', type: 'bearish', title: '{industry}传出一家公司欠薪的消息，同行股价跟着抖', desc: '虽然只是个别公司的问题，但「城门失火殃及池鱼」。', impact: { '行业景气': -0.02 }, industry: true, duration: 2 },
    { stage: [0], cat: 'industry', type: 'bullish', title: '{industry}头部公司开年会抽奖，奖品是「股票期权」', desc: '中奖员工当场激动落泪，说「这就是传说中的金手铐」。', impact: { '行业景气': 0.015 }, industry: true, duration: 1 },
    { stage: [0], cat: 'industry', type: 'neutral', title: '{industry}行业峰会排队入场，黄牛票炒到三倍价', desc: '主办方回应：下次扩容，大家别买黄牛票。', impact: { '行业景气': 0.01 }, industry: true, duration: 1 },
    { stage: [0], cat: 'industry', type: 'bullish', title: '{industry}出口订单激增，工厂加班加点赶工', desc: '工人师傅说「累并快乐着」，加班费给得足。', impact: { '行业景气': 0.025, '国际环境': 0.01 }, industry: true, duration: 3 },
    { stage: [0], cat: 'industry', type: 'bearish', title: '{industry}行业大佬在朋友圈发了一句「冬天来了」', desc: '配图是一杯热茶，市场却解读为行业要降温。', impact: { '行业景气': -0.02 }, industry: true, duration: 2 },
    { stage: [0], cat: 'industry', type: 'neutral', title: '{industry}技能大赛开赛，冠军奖金 10 万', desc: '选手们摩拳擦掌，行业人才储备备受关注。', impact: { '行业景气': 0.008 }, industry: true, duration: 1 },
    { stage: [0], cat: 'industry', type: 'bullish', title: '{industry}新国标发布，龙头公司率先响应', desc: '标准升级利好头部玩家，行业集中度有望提升。', impact: { '行业景气': 0.02, '政策风险': 0.01 }, industry: true, duration: 3 },
    { stage: [0], cat: 'industry', type: 'bearish', title: '{industry}原材料涨价，中小企业叫苦不迭', desc: '成本压力传导，部分小厂开始收缩产能。', impact: { '行业景气': -0.02, '宏观经济': -0.005 }, industry: true, duration: 2 },
    { stage: [0], cat: 'industry', type: 'neutral', title: '{industry}行业协会发布了年度「最佳雇主」榜单', desc: '上榜公司招聘页面访问量暴增，人才争夺战加剧。', impact: { '行业景气': 0.008 }, industry: true, duration: 1 },
    { stage: [0], cat: 'industry', type: 'bullish', title: '{industry}诞生了一批「网红公司」，年轻人挤破头想进', desc: '社交平台上晒工牌成风潮，行业热度肉眼可见。', impact: { '行业景气': 0.02, '市场情绪': 0.01 }, industry: true, duration: 2 },
    { stage: [0], cat: 'rumor', type: 'bullish', title: '股吧热帖：{company}老板是「锦鲤体质」，跟买不亏', desc: '帖子虽然充满玄学色彩，但跟风买入的人还真不少。', impact: { '市场情绪': 0.015 }, symbol: true, duration: 1 },
    { stage: [0], cat: 'rumor', type: 'neutral', title: '传闻某大佬在酒桌上点名看好{industry}', desc: '具体说了什么没人记得清，反正「看好」两个字传出来了。', impact: { '市场情绪': 0.01 }, industry: true, duration: 1 },
    { stage: [0], cat: 'rumor', type: 'bearish', title: '小道消息：{company}董事长最近老往医院跑', desc: '后来证实是去体检，但股价还是被吓了一跌。', impact: { '公司特质': -0.02 }, symbol: true, duration: 1 },
    { stage: [0], cat: 'rumor', type: 'bullish', title: '网传{company}要出联名款，评论区都在猜和谁联名', desc: '公司回应「敬请期待」，吊足了胃口。', impact: { '公司特质': 0.015 }, symbol: true, duration: 2 },
    { stage: [0], cat: 'rumor', type: 'neutral', title: '玄学大师预言：本周{industry}运势「上上签」', desc: '虽然不科学，但当天{industry}板块确实红了。', impact: { '市场情绪': 0.01 }, industry: true, duration: 1 },
    { stage: [0], cat: 'policy', type: 'bullish', title: '地方给新上市公司发补贴，红包雨下个不停', desc: '企业纷纷晒出到账截图，市场气氛热烈。', impact: { '政策风险': -0.01, '市场情绪': 0.015 }, duration: 2 },
    { stage: [0], cat: 'policy', type: 'neutral', title: '监管层宣布简化上市流程，给市场松绑', desc: '企业上市更便捷，券商投行业务量看涨。', impact: { '政策风险': -0.01, '市场情绪': 0.01 }, duration: 3 },
    { stage: [0], cat: 'policy', type: 'bearish', title: '监管喊话：警惕「过热炒作」，市场降温', desc: '消息一出，连板股纷纷炸板，游资集体撤退。', impact: { '政策风险': -0.02, '市场情绪': -0.02 }, duration: 2 },
    { stage: [0], cat: 'policy', type: 'neutral', title: '交易所优化交易规则，减少「乌龙指」发生', desc: '散户拍手叫好，量化机构则要重新适配策略。', impact: { '政策风险': 0.005 }, duration: 2 },

    // ════════════════ 成长：渐正式 ════════════════
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}发布季报：营收同比增长{C}%，净利润增速回升', desc: '管理层在电话会上表示，订单能见度高，全年目标有望超额完成。', impact: { '公司特质': 0.03, '行业景气': 0.01 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '多家机构将{company}评级上调至「买入」，目标价上调{C}%', desc: '研报认为公司护城河稳固，当前估值具备吸引力，建议逢低布局。', impact: { '公司特质': 0.025, '市场情绪': 0.01 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}宣布新品发布会定档，渠道备货积极', desc: '渠道反馈预订量超出预期，分析师称需观察实际转化率。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}遭大股东减持公告，套现约{C}亿元', desc: '公告称系个人资金需求，市场解读为短期利空，股价承压。', impact: { '公司特质': -0.03 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}中标重大项目，金额约{C}亿元', desc: '合同标的为行业标杆项目，验证公司技术实力与行业地位。', impact: { '公司特质': 0.03 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}宣布回购计划，金额不超过{C}亿元', desc: '回购彰显信心，短期对股价形成支撑。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}卷入诉讼纠纷，或面临{C}亿元赔偿', desc: '案件尚在审理，公司称已计提相关准备，但市场情绪谨慎。', impact: { '公司特质': -0.025 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}与行业龙头达成战略合作', desc: '双方将共建产业生态，市场认为协同效应显著。', impact: { '公司特质': 0.025, '行业景气': 0.01 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}管理层增持股票{C}万股', desc: '高管真金白银买入，向市场传递长期信心。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}被曝产品质量问题，召回部分产品', desc: '公司启动应急预案，但短期销售或受影响。', impact: { '公司特质': -0.03 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}海外市场取得突破，拿下{C}亿美元订单', desc: '国际化战略再进一步，海外收入占比有望提升。', impact: { '公司特质': 0.03, '国际环境': 0.01 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}完成新一轮定增，募资{C}亿元', desc: '资金将用于产能扩张与研发投入，摊薄效应有限。', impact: { '公司特质': 0.015 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}研发负责人离职，市场担忧技术团队稳定', desc: '公司回应称交接顺利，但股价仍出现波动。', impact: { '公司特质': -0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}产品市占率提升至行业前三', desc: '第三方机构数据显示，公司市场份额持续提升，竞争力增强。', impact: { '公司特质': 0.025, '行业景气': 0.01 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}获得高新技术企业认证，享税收优惠', desc: '所得税率下调将增厚利润，利好程度视规模而定。', impact: { '公司特质': 0.015 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}一季报业绩不及预期，股价低开', desc: '受行业需求疲软影响，公司下调全年指引。', impact: { '公司特质': -0.035 }, symbol: true, duration: 3 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}员工持股计划落地，覆盖核心骨干', desc: '利益绑定有助于稳定团队，市场反应积极。', impact: { '公司特质': 0.018 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}变更注册资本，完成工商登记', desc: '常规事项，市场关注度有限，股价平稳。', impact: {}, duration: 1 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}被媒体质疑财务数据，公司连夜回应', desc: '公司称报道失实并保留追责权利，风波暂未平息。', impact: { '公司特质': -0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}获评行业「年度创新企业」', desc: '奖项背后是持续的研发投入，机构给予积极评价。', impact: { '公司特质': 0.015 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}召开股东大会，通过年度利润分配方案', desc: '分红比例符合预期，散户股东普遍满意。', impact: { '公司特质': 0.01 }, symbol: true, duration: 1 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}新产线投产，产能提升{C}%', desc: '产能瓶颈解除，为后续订单增长提供保障。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'bearish', title: '{company}客户集中度风险暴露，大客户砍单', desc: '公司称正积极拓展新客户，短期收入承压。', impact: { '公司特质': -0.025 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'company', type: 'neutral', title: '{company}举办投资者开放日，高管直面提问', desc: '交流坦诚，市场对公司治理评价提升。', impact: { '公司特质': 0.01 }, symbol: true, duration: 1 },
    { stage: [1, 2], cat: 'company', type: 'bullish', title: '{company}毛利率连续三个季度提升', desc: '产品结构优化叠加成本控制见效，盈利质量改善。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'bullish', title: '央行开展中期借贷便利操作，投放{C}亿元流动性', desc: '机构认为货币政策维持宽松基调，对权益市场构成支撑。', impact: { '宏观经济': 0.02, '市场情绪': 0.01 }, duration: 3 },
    { stage: [1, 2], cat: 'macro', type: 'neutral', title: '国家统计局：{industry}景气指数连续两月回升', desc: '数据显示行业订单与产能利用率同步改善，复苏趋势确立。', impact: { '行业景气': 0.02 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'macro', type: 'bullish', title: '北向资金连续{N}日净流入，重点加仓{industry}板块', desc: '外资定价权逐步提升，核心资产获增量资金青睐。', impact: { '市场情绪': 0.015 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'neutral', title: '社融数据出炉：增量略超预期', desc: '信贷结构改善，企业中长贷同比多增，经济动能回升。', impact: { '宏观经济': 0.015 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'bearish', title: 'CPI 同比上涨{C}%，通胀压力隐现', desc: '食品与能源价格抬升，市场担忧货币政策空间收窄。', impact: { '宏观经济': -0.015 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'bullish', title: 'PMI 重回荣枯线上方，制造业景气回升', desc: '新订单与生产指数同步改善，经济复苏信号增强。', impact: { '宏观经济': 0.02 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'neutral', title: 'LPR 报价维持不变，符合市场预期', desc: '政策面保持定力，市场利率平稳。', impact: { '宏观经济': 0.005 }, duration: 1 },
    { stage: [1, 2], cat: 'macro', type: 'bearish', title: 'M2 增速回落，市场担忧流动性收紧', desc: '央行回应称「稳健取向不变」，但资金面边际趋紧。', impact: { '宏观经济': -0.015, '市场情绪': -0.01 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'bullish', title: '进出口数据超预期，外贸韧性凸显', desc: '出口链相关板块走强，人民币汇率保持稳定。', impact: { '宏观经济': 0.015, '国际环境': 0.01 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'neutral', title: '财新制造业 PMI 微升，中小企业景气改善', desc: '大中小企业分化收窄，经济内生动力增强。', impact: { '宏观经济': 0.01 }, duration: 1 },
    { stage: [1, 2], cat: 'macro', type: 'bullish', title: '工业企业利润同比增长{C}%，盈利修复加快', desc: '上游让利叠加需求回暖，中下游利润改善明显。', impact: { '宏观经济': 0.02 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'bearish', title: '地产投资持续低迷，拖累固定资产投资', desc: '地产链相关板块承压，宏观增长预期下修。', impact: { '宏观经济': -0.02 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'neutral', title: '就业数据平稳，调查失业率小幅波动', desc: '服务业吸纳就业能力增强，结构性问题仍存。', impact: { '宏观经济': 0.005 }, duration: 1 },
    { stage: [1, 2], cat: 'macro', type: 'bullish', title: '财政发力：专项债发行提速', desc: '基建投资有望托底经济，相关板块迎来机会。', impact: { '宏观经济': 0.02 }, duration: 2 },
    { stage: [1, 2], cat: 'macro', type: 'bearish', title: '人民币汇率短期波动加大，北向资金流出', desc: '汇率波动影响外资情绪，核心资产承压。', impact: { '国际环境': -0.02, '市场情绪': -0.01 }, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bullish', title: '{industry}订单回暖，龙头排产满负荷', desc: '下游补库需求释放，行业景气度明显回升。', impact: { '行业景气': 0.025 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'industry', type: 'neutral', title: '{industry}价格指数企稳，成本压力缓解', desc: '原材料价格回落，企业盈利空间边际改善。', impact: { '行业景气': 0.015 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bearish', title: '{industry}库存高企，去化压力加大', desc: '渠道库存积压，企业或降价促销，利润承压。', impact: { '行业景气': -0.02 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bullish', title: '{industry}技术突破：核心参数刷新纪录', desc: '技术迭代加速，行业有望打开新成长空间。', impact: { '行业景气': 0.03 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'industry', type: 'neutral', title: '{industry}并购整合潮起，头部集中度提升', desc: '行业洗牌加速，中小玩家面临出清压力。', impact: { '行业景气': 0.01 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bearish', title: '{industry}海外需求走弱，出口订单回落', desc: '海外经济放缓拖累出口，行业增速预期下修。', impact: { '行业景气': -0.02, '国际环境': -0.01 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bullish', title: '{industry}新应用场景放量，打开第二增长曲线', desc: '传统业务之外的新兴需求爆发，行业想象空间打开。', impact: { '行业景气': 0.025 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'industry', type: 'neutral', title: '{industry}人才流动加剧，高薪挖人成常态', desc: '行业竞争白热化，人力成本上升压力显现。', impact: { '行业景气': 0.008 }, industry: true, duration: 1 },
    { stage: [1, 2], cat: 'industry', type: 'bearish', title: '{industry}安全事故频发，行业整改进行时', desc: '监管趋严，部分产能面临停产整顿风险。', impact: { '行业景气': -0.025, '政策风险': -0.01 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'industry', type: 'bullish', title: '{industry}出口退税上调，海外竞争力增强', desc: '政策利好直接增厚出口企业利润，板块应声走强。', impact: { '行业景气': 0.02, '政策风险': 0.01 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'neutral', title: '{industry}标准更新在即，企业加速适配', desc: '新标准实施临近，头部企业有望率先受益。', impact: { '行业景气': 0.01 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bullish', title: '{industry}海外展会收获颇丰，意向订单翻倍', desc: '参展企业普遍反馈「这届展会含金量高」，出海预期升温。', impact: { '行业景气': 0.02, '国际环境': 0.01 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'bearish', title: '{industry}价格战再起，利润率被压缩', desc: '行业竞争加剧，以价换量成为主旋律，盈利承压。', impact: { '行业景气': -0.02 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'industry', type: 'neutral', title: '{industry}第三方检测机构发布质量抽检结果', desc: '结果整体向好，个别企业需整改，市场反应平稳。', impact: { '行业景气': 0.005 }, industry: true, duration: 1 },
    { stage: [1, 2], cat: 'policy', type: 'neutral', title: '监管部门就{industry}行业融资新规征求意见', desc: '新规旨在规范行业融资行为，中长期利好头部企业。', impact: { '政策风险': 0.01, '行业景气': 0.01 }, industry: true, duration: 4 },
    { stage: [1, 2], cat: 'policy', type: 'bullish', title: '新一批{industry}产业扶持政策落地，补贴力度加大', desc: '符合条件企业可获专项资金支持，产业链相关公司直接受益。', impact: { '行业景气': 0.03, '政策风险': -0.01 }, industry: true, duration: 4 },
    { stage: [1, 2], cat: 'policy', type: 'bearish', title: '监管收紧{industry}领域审批，新增产能受限', desc: '供给侧约束趋严，存量产能价值提升，短期供给冲击。', impact: { '政策风险': -0.02, '行业景气': 0.01 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'policy', type: 'neutral', title: '{industry}行业标准修订公开征求意见', desc: '标准趋严将淘汰落后产能，头部企业受益。', impact: { '政策风险': 0.005, '行业景气': 0.01 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'policy', type: 'bullish', title: '税收优惠扩围：{industry}企业所得税减免', desc: '直接增厚利润，行业整体盈利能力提升。', impact: { '政策风险': -0.015, '行业景气': 0.02 }, industry: true, duration: 3 },
    { stage: [1, 2], cat: 'policy', type: 'bearish', title: '环保督察进驻{industry}，部分工厂停产整顿', desc: '供给阶段性收缩，产品价格或上涨，但龙头盈利短期受损。', impact: { '政策风险': -0.02 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'policy', type: 'neutral', title: '证监会：支持{industry}优质企业上市融资', desc: '政策表态积极，相关企业上市进程有望提速。', impact: { '政策风险': -0.01, '市场情绪': 0.01 }, industry: true, duration: 2 },
    { stage: [1, 2], cat: 'policy', type: 'bullish', title: '多部门联合发布{industry}发展行动计划', desc: '目标明确、路径清晰，行业迎来政策东风。', impact: { '行业景气': 0.025, '政策风险': -0.01 }, industry: true, duration: 4 },

    // ════════════════ 成熟：专业财经 ════════════════
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}披露年报：营收创历史新高，拟每10股派现{C}元', desc: '业绩符合甚至略超预期，分红比例提升彰显股东回报意愿。', impact: { '公司特质': 0.035, '市场情绪': 0.015 }, symbol: true, duration: 4 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}宣布回购计划，金额不超过{C}亿元', desc: '回购价格上限较现价溢价约15%，传递管理层信心。', impact: { '公司特质': 0.03 }, symbol: true, duration: 3 },
    { stage: [2], cat: 'company', type: 'neutral', title: '{company}子公司获重大合同，订单金额约{C}亿元', desc: '合同履行周期约两年，对当期业绩影响有限，但打开成长空间。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}因会计差错收监管函，股价承压', desc: '公司回应称系口径调整，不影响经营基本面，但市场情绪偏谨慎。', impact: { '公司特质': -0.025 }, symbol: true, duration: 3 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}业绩预告：全年净利润预增{C}%', desc: '业绩超预期，机构纷纷上调盈利预测与目标价。', impact: { '公司特质': 0.035, '市场情绪': 0.01 }, symbol: true, duration: 3 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}业绩预告：净利润预减{C}%', desc: '公司归因于行业下行与计提减值，市场下调预期。', impact: { '公司特质': -0.03 }, symbol: true, duration: 3 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}拟收购同业资产，交易对价{C}亿元', desc: '并购将补齐产品线短板，协同效应值得期待，尚需监管审批。', impact: { '公司特质': 0.025 }, symbol: true, duration: 4 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}并购重组被否决，方案宣告终止', desc: '公司表示尊重监管决定，将专注内生增长。', impact: { '公司特质': -0.02 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}获社保基金增持，长期资金进场', desc: '长线资金配置价值凸显，市场信心增强。', impact: { '公司特质': 0.02, '市场情绪': 0.01 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'neutral', title: '{company}董监高换届落定，管理层保持稳定', desc: '新一届班子延续既定战略，市场反应平稳。', impact: { '公司特质': 0.005 }, symbol: true, duration: 1 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}控股股东质押比例过高，引发担忧', desc: '公司回应称质押风险可控，但市场情绪仍受影响。', impact: { '公司特质': -0.015 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}纳入重要指数成分股，被动资金流入', desc: '指数基金配置需求带来增量买盘，流动性改善。', impact: { '公司特质': 0.02, '市场情绪': 0.01 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'neutral', title: '{company}股东大会通过员工持股计划', desc: '员工利益与股东利益进一步绑定，长期利好。', impact: { '公司特质': 0.01 }, symbol: true, duration: 1 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}被境外机构做空，发布做空报告', desc: '公司逐条回应质疑，股价大幅波动后企稳。', impact: { '公司特质': -0.03, '国际环境': -0.01 }, symbol: true, duration: 3 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}技术专利获国际认可，授权收入增长', desc: '专利转化落地，技术变现能力得到验证。', impact: { '公司特质': 0.025 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'neutral', title: '{company}发布 ESG 报告，评级上调', desc: '治理与环保表现获认可，机构配置偏好改善。', impact: { '公司特质': 0.01 }, symbol: true, duration: 1 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}主要产品遭竞品降价冲击，份额承压', desc: '行业竞争加剧，公司或需调整定价策略。', impact: { '公司特质': -0.02 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'bullish', title: '{company}现金流大幅改善，自由现金流创历史新高', desc: '盈利质量提升，为分红与再投资提供坚实支撑。', impact: { '公司特质': 0.02 }, symbol: true, duration: 2 },
    { stage: [2], cat: 'company', type: 'neutral', title: '{company}披露关联交易公告，金额{C}亿元', desc: '交易定价公允，符合商业惯例，市场关注度有限。', impact: {}, duration: 1 },
    { stage: [2], cat: 'company', type: 'bearish', title: '{company}半年报计提大额减值，净利润转亏', desc: '公司称系审慎处理历史包袱，为轻装上阵做准备。', impact: { '公司特质': -0.035 }, symbol: true, duration: 3 },
    { stage: [2], cat: 'macro', type: 'bullish', title: '央行宣布降准{C}个百分点，释放长期资金约{C}万亿元', desc: '这是年内第{C}次降准，机构解读为稳增长政策加码。', impact: { '宏观经济': 0.03, '市场情绪': 0.02 }, duration: 5 },
    { stage: [2], cat: 'macro', type: 'neutral', title: '统计局：三季度GDP同比增长{C}%，好于市场预期', desc: '消费与出口韧性较强，制造业投资保持较高增速。', impact: { '宏观经济': 0.015 }, duration: 3 },
    { stage: [2], cat: 'macro', type: 'bearish', title: '美联储维持利率不变但措辞鹰派，全球风险资产承压', desc: '美债收益率上行，外资流出压力加大，成长板块估值受压制。', impact: { '国际环境': -0.025, '市场情绪': -0.015 }, duration: 4 },
    { stage: [2], cat: 'macro', type: 'bearish', title: '国际油价大幅波动，通胀预期升温', desc: '能源成本上升挤压中下游利润，周期与消费板块受波及。', impact: { '宏观经济': -0.02, '国际环境': -0.01 }, duration: 3 },
    { stage: [2], cat: 'macro', type: 'neutral', title: '央行开展{C}亿元逆回购操作，维护流动性合理充裕', desc: '公开市场操作精准滴灌，资金面保持平稳。', impact: { '宏观经济': 0.01 }, duration: 1 },
    { stage: [2], cat: 'macro', type: 'bullish', title: '财政收入增速回升，积极财政持续发力', desc: '财政支出向民生与基建倾斜，稳增长信号明确。', impact: { '宏观经济': 0.015 }, duration: 2 },
    { stage: [2], cat: 'macro', type: 'bearish', title: '信贷投放不及预期，实体融资需求偏弱', desc: '企业扩张意愿不足，经济复苏斜率放缓。', impact: { '宏观经济': -0.02 }, duration: 2 },
    { stage: [2], cat: 'macro', type: 'neutral', title: '外汇储备保持稳定，跨境资金流动平稳', desc: '外部环境复杂但整体可控，市场信心未受明显冲击。', impact: { '国际环境': 0.005 }, duration: 1 },
    { stage: [2], cat: 'macro', type: 'bullish', title: '制造业投资同比增长{C}%，结构持续优化', desc: '高技术产业投资高速增长，经济新动能不断积蓄。', impact: { '宏观经济': 0.02 }, duration: 2 },
    { stage: [2], cat: 'macro', type: 'bearish', title: '消费增速放缓，内需修复不及预期', desc: '居民消费意愿偏弱，政策或加码促消费。', impact: { '宏观经济': -0.02, '消费景气': -0.01 }, duration: 2 },
    { stage: [2], cat: 'macro', type: 'neutral', title: '中美利差收窄，人民币汇率双向波动', desc: '汇率弹性增强，对出口企业影响温和。', impact: { '国际环境': 0.005 }, duration: 1 },
    { stage: [2], cat: 'macro', type: 'bullish', title: '国家出台新质生产力扶持方案', desc: '科技成长板块迎政策催化，相关产业链受益明显。', impact: { '行业景气': 0.02, '政策风险': -0.01 }, duration: 3 },
    { stage: [2], cat: 'macro', type: 'bearish', title: '全球贸易摩擦升温，出口链承压', desc: '关税与贸易限制增加不确定性，外向型企业盈利承压。', impact: { '国际环境': -0.025 }, duration: 3 },
    { stage: [2], cat: 'macro', type: 'neutral', title: '中央经济工作会议定调：稳中求进', desc: '政策取向明确，市场预期趋于稳定。', impact: { '宏观经济': 0.01 }, duration: 2 },
    { stage: [2], cat: 'macro', type: 'bullish', title: '专项债发行放量，基建投资提速', desc: '实物工作量加快形成，上游周期与建材板块受益。', impact: { '宏观经济': 0.02 }, duration: 2 },
    { stage: [2], cat: 'macro', type: 'bearish', title: '大宗商品价格飙升，输入性通胀压力加大', desc: '中下游企业成本压力陡增，利润空间受挤压。', impact: { '宏观经济': -0.02 }, duration: 2 },
    { stage: [2], cat: 'policy', type: 'neutral', title: '全面注册制下退市新规落地，市场分化加剧', desc: '壳价值持续缩水，基本面成为资金最重要的锚。', impact: { '政策风险': 0.01 }, duration: 4 },
    { stage: [2], cat: 'policy', type: 'bearish', title: '证监会：严查场外配资与违规减持', desc: '短期资金面承压，杠杆资金加速离场，指数震荡回调。', impact: { '政策风险': -0.025, '市场情绪': -0.02 }, duration: 3 },
    { stage: [2], cat: 'policy', type: 'bullish', title: '多地出台楼市新政，房地产板块异动拉升', desc: '限购松绑与信贷支持并举，地产链预期回暖。', impact: { '宏观经济': 0.02 }, industry: true, duration: 3 },
    { stage: [2], cat: 'policy', type: 'bearish', title: '反垄断监管加码，平台经济承压', desc: '相关企业短期面临整改压力，板块估值下修。', impact: { '政策风险': -0.02 }, duration: 3 },
    { stage: [2], cat: 'policy', type: 'neutral', title: '新《证券法》配套细则出台', desc: '投资者保护力度加强，市场生态持续净化。', impact: { '政策风险': 0.005 }, duration: 2 },
    { stage: [2], cat: 'policy', type: 'bullish', title: '险资入市比例上限上调，长线资金扩容', desc: '增量资金入市预期升温，蓝筹权重股受益。', impact: { '市场情绪': 0.02 }, duration: 3 },
    { stage: [2], cat: 'policy', type: 'bearish', title: '监管窗口指导：放缓新股发行节奏', desc: '短期缓解供给压力，但长期融资功能或受影响。', impact: { '市场情绪': 0.015 }, duration: 2 },
    { stage: [2], cat: 'policy', type: 'neutral', title: '个人养老金投资范围扩容至权益市场', desc: '长期资金入市渠道拓宽，A 股机构化进程加快。', impact: { '市场情绪': 0.015 }, duration: 2 },
    { stage: [2], cat: 'policy', type: 'bullish', title: '上市公司分红新规：鼓励中期分红', desc: '高分红公司获资金青睐，红利策略走强。', impact: { '市场情绪': 0.015 }, duration: 2 },
    { stage: [2], cat: 'international', type: 'bearish', title: '地缘局势升温，避险资产走高，风险资产承压', desc: '黄金原油走强，全球股市普跌，北向资金转为流出。', impact: { '国际环境': -0.03, '市场情绪': -0.02 }, duration: 4 },
    { stage: [2], cat: 'international', type: 'bullish', title: '主要经济体达成贸易协议，出口链预期改善', desc: '关税压力缓解，出口企业有望直接受益。', impact: { '国际环境': 0.025 }, industry: true, duration: 3 },
    { stage: [2], cat: 'international', type: 'neutral', title: '美元指数走弱，新兴市场资金回流', desc: '人民币资产吸引力提升，外资配置意愿增强。', impact: { '国际环境': 0.015 }, duration: 2 },
    { stage: [2], cat: 'international', type: 'bearish', title: '海外供应链中断，部分产业缺芯缺料', desc: '供给瓶颈制约产出，相关企业成本上升。', impact: { '国际环境': -0.02, '行业景气': -0.01 }, duration: 3 },
    { stage: [2], cat: 'international', type: 'bullish', title: '海外巨头追加在华投资，产业合作深化', desc: '外资持续看好中国市场，相关产业链受益。', impact: { '国际环境': 0.02, '市场情绪': 0.01 }, duration: 2 },
    { stage: [2], cat: 'international', type: 'neutral', title: '全球央行年会举行，主要央行政策基调偏鸽', desc: '全球流动性宽松预期升温，风险偏好改善。', impact: { '国际环境': 0.015 }, duration: 2 },
    { stage: [2], cat: 'international', type: 'bearish', title: '海外科技制裁升级，产业链自主可控紧迫', desc: '相关板块短期承压，但国产替代逻辑强化。', impact: { '国际环境': -0.02, '行业景气': 0.01 }, duration: 3 },
    { stage: [2], cat: 'international', type: 'bullish', title: '人民币国际结算份额提升', desc: '人民币资产吸引力增强，跨境资金流入增加。', impact: { '国际环境': 0.015 }, duration: 2 },
    { stage: [2], cat: 'international', type: 'neutral', title: 'G20 峰会就稳定全球供应链达成共识', desc: '外部不确定性边际缓解，市场情绪回暖。', impact: { '国际环境': 0.01 }, duration: 2 },
    { stage: [2], cat: 'industry', type: 'bullish', title: '{industry}行业景气度上行，机构上调盈利预测', desc: '量价齐升，行业盈利弹性释放，龙头率先受益。', impact: { '行业景气': 0.025 }, industry: true, duration: 3 },
    { stage: [2], cat: 'industry', type: 'bearish', title: '{industry}行业进入下行周期，需求走弱', desc: '产能过剩隐忧显现，行业盈利承压，估值下修。', impact: { '行业景气': -0.025 }, industry: true, duration: 3 },
    { stage: [2], cat: 'industry', type: 'neutral', title: '{industry}竞争格局生变，新进入者搅局', desc: '跨界玩家入场，行业集中度或重新洗牌。', impact: { '行业景气': 0.005 }, industry: true, duration: 2 },
    { stage: [2], cat: 'industry', type: 'bullish', title: '{industry}出海提速，海外收入占比创新高', desc: '全球化布局见效，行业成长天花板进一步打开。', impact: { '行业景气': 0.02, '国际环境': 0.01 }, industry: true, duration: 3 },
    { stage: [2], cat: 'industry', type: 'bearish', title: '{industry}库存周期见顶，补库结束', desc: '需求端动能减弱，行业进入被动累库阶段。', impact: { '行业景气': -0.02 }, industry: true, duration: 2 },
    { stage: [2], cat: 'industry', type: 'neutral', title: '{industry}龙头发布指引：未来增速放缓至{C}%', desc: '行业进入成熟期，增长逻辑从速度转向质量。', impact: { '行业景气': 0.005 }, industry: true, duration: 2 },
    { stage: [2], cat: 'industry', type: 'bullish', title: '{industry}技术路线确立，行业标准加速统一', desc: '标准明确降低产业不确定性，规模化拐点临近。', impact: { '行业景气': 0.02 }, industry: true, duration: 3 },
    { stage: [2], cat: 'industry', type: 'bearish', title: '{industry}海外市场受阻，出口认证遇瓶颈', desc: '合规门槛提高，企业出海节奏放缓。', impact: { '行业景气': -0.02, '国际环境': -0.01 }, industry: true, duration: 2 },
    { stage: [2], cat: 'industry', type: 'neutral', title: '{industry}上市公司业绩分化加剧', desc: '龙头集中度提升，尾部企业加速出清。', impact: { '行业景气': 0.005 }, industry: true, duration: 1 },
    { stage: [2], cat: 'industry', type: 'bullish', title: '{industry}政策补贴加码，行业渗透率加速提升', desc: '需求催化叠加政策红利，行业景气持续向好。', impact: { '行业景气': 0.025, '政策风险': -0.01 }, industry: true, duration: 4 },
];
